const translations: Record<string, string> = {
    // 工具栏 (Palette) & 核心节点
    'Activate the create/remove space tool': '激活创建/删除空间工具',
    'Activate the global connect tool': '激活全局连接工具',
    'Activate the hand tool': '激活抓手工具',
    'Activate the lasso tool': '激活套索工具',
    'Activate the lasso tool (L)': '激活套索工具 (L)',
    'Activate the selection tool': '激活选择工具',
    'Add Lane above': '在上方添加泳道',
    'Add Lane below': '在下方添加泳道',
    'Append EndEvent': '追加结束事件',
    'Append Gateway': '追加网关',
    'Append Intermediate/Boundary Event': '追加中间/边界事件',
    'Append Task': '追加任务',
    'Append cond-task': '追加条件任务',
    'Append message-intermediate-catch-event': '追加捕获消息事件',
    'Append receive-task': '追加接收任务',
    'Append rect': '追加矩形',
    'Append task': '追加任务',
    'Append text-annotation': '追加文本批注',
    'Append {type}': '追加 {type}',
    'Business Rule Task': '业务规则任务',
    'Call Activity': '调用活动',
    'Cancel End Event': '取消结束事件',
    'Change type': '更改类型',
    'Conditional Boundary Event': '条件边界事件',
    'Conditional Intermediate Catch Event': '条件中间捕获事件',
    'Conditional Start Event': '条件启动事件',
    'Connect': '连接',
    'Create Boundary Event': '创建边界事件',
    'Create EndEvent': '创建结束事件',
    'Create Gateway': '创建网关',
    'Create Intermediate/Boundary Event': '创建中间/边界事件',
    'Create IntermediateThrowEvent/BoundaryEvent': '创建中间抛出/边界事件',
    'Create Pool/Participant': '创建池/参与者',
    'Create StartEvent': '创建开始事件',
    'Create Task': '创建任务',
    'Create expanded SubProcess': '创建展开的子流程',
    'Create labled-ellipse': '创建带标签的椭圆',
    'Create rect': '创建矩形',
    'Create task': '创建任务',
    'Create text-annotation': '创建文本批注',
    'Create {type}': '创建 {type}',
    'Divide into three Lanes': '分成三条泳道',
    'Divide into two Lanes': '分成两条泳道',
    'End Event': '结束事件',
    'Error Boundary Event': '错误边界事件',
    'Error End Event': '错误结束事件',
    'Error Start Event': '错误启动事件',
    'Escalation Boundary Event': '升级边界事件',
    'Escalation End Event': '升级结束事件',
    'Escalation Intermediate Throw Event': '升级中间抛出事件',
    'Escalation Start Event': '升级启动事件',
    'Exclusive Gateway': '排他网关',
    'Hand Tool': '抓手工具',
    'Inclusive Gateway': '相容网关',
    'Intermediate Throw Event': '中间抛出事件',
    'Lasso Tool': '套索工具',
    'Link Intermediate Catch Event': '链接中间捕获事件',
    'Link Intermediate Throw Event': '链接中间抛出事件',
    'Loop': '循环',
    'Manual Task': '手动任务',
    'Message Boundary Event': '消息边界事件',
    'Message End Event': '消息结束事件',
    'Message Intermediate Catch Event': '消息中间捕获事件',
    'Message Intermediate Throw Event': '消息中间抛出事件',
    'Message Start Event': '消息启动事件',
    'Parallel Gateway': '并行网关',
    'Parallel Multiple Boundary Event': '并行多重边界事件',
    'Parallel Multiple Start Event': '并行多重启动事件',
    'Receive Task': '接收任务',
    'Remove': '删除',
    'Script Task': '脚本任务',
    'Send Task': '发送任务',
    'Service Task': '服务任务',
    'Signal Boundary Event': '信号边界事件',
    'Signal End Event': '信号结束事件',
    'Signal Intermediate Catch Event': '信号中间捕获事件',
    'Signal Intermediate Throw Event': '信号中间抛出事件',
    'Signal Start Event': '信号启动事件',
    'Space Tool': '空间工具',
    'Start Event': '开始事件',
    'Sub Process': '子流程',
    'Sub Process (collapsed)': '子流程 (折叠)',
    'Sub Process (expanded)': '子流程 (展开)',
    'Task': '任务',
    'Terminate End Event': '终止结束事件',
    'Text Annotation': '文本批注',
    'Timer Boundary Event': '定时边界事件',
    'Timer Intermediate Catch Event': '定时中间捕获事件',
    'Timer Start Event': '定时启动事件',
    'Transaction': '事务',
    'User Task': '用户任务',

    // 属性面板 (Properties Panel) - 汉化常见英文
    'General': '常规',
    'Documentation': '文档',
    'Element Documentation': '元素文档',
    'Extension properties': '扩展属性',
    'Extension Properties': '扩展属性',
    'Executable': '可执行',
    'Process Id': '流程 ID',
    'Process Name': '流程名称',
    'Process ID': '流程 ID',
    'Process name': '流程名称',
    'Version Tag': '版本标签',
    'Version tag': '版本标签',
    'Task Listener': '任务监听器',
    'Task listeners': '任务监听器',
    'Execution Listener': '执行监听器',
    'Execution listeners': '执行监听器',
    'Event Type': '事件类型',
    'Listener Type': '监听器类型',
    'Java Class': 'Java 类',
    'Expression': '表达式',
    'Delegate Expression': '委托表达式',
    'Fields': '字段',
    'Field Injection': '字段注入',
    'Type': '类型',
    'Value': '值',
    'String': '字符串',
    'Candidate Users': '候选用户',
    'Candidate Groups': '候选组',
    'Assignee': '处理人',
    'Due Date': '到期时间',
    'Follow Up Date': '跟进时间',
    'Priority': '优先级',
    'Forms': '表单',
    'Form Key': '表单 Key',
    'Form Field': '表单字段',
    'Form Fields': '表单字段',
    'Id': 'Id',
    'ID': 'ID',
    'Label': '标签',
    'Default Value': '默认值',
    'Default value': '默认值',
    'Validation': '验证',
    'Constraints': '约束',
    'Properties': '属性',
    'Property': '属性',
    'Asynchronous Before': '异步在前',
    'Asynchronous After': '异步在后',
    'Exclusive': '排他 (Exclusive)',
    'Job Configuration': '作业配置',
    'Job Priority': '作业优先级',
    'Retry Time Cycle': '重试时间周期',
    'External Task': '外部任务',
    'Topic': '主题 (Topic)',
    'Multi Instance': '多实例',
    'Multi-instance': '多实例',
    'Loop Cardinality': '循环基数',
    'Collection': '集合',
    'Element Variable': '元素变量',
    'Completion Condition': '完成条件',
    'Available process variables': '可用流程变量',

    // 常用按钮与常规文本
    'Create': '创建',
    'Expand': '展开',
    'Add': '添加',
    'Remove Element': '移除元素',
    'Save': '保存',
    'Cancel': '取消',
    'Close': '关闭',
    'Select': '选择',
    'Details': '详情',
    'Script': '脚本',
    'Condition': '条件',
    'Timer': '定时器',
    'Signal': '信号',
    'Message': '消息',
    'Error': '错误',
    'Escalation': '升级',
    'Compensate': '补偿',
    'Link': '链接',
    'Conditional': '条件',
    'Parallel': '并行',
    'None': '无',
    'Sequential': '串行',

    // Flowable / Camunda 专属
    'Category': '类别',
    'History Cleanup': '历史清理',
    'Task Priority': '任务优先级',
    'Description': '描述',
    'initiator': '发起人',
    'candidateUsers': '候选用户',
    'candidateGroups': '候选组',
    'assignee': '处理人',
    'formKey': '表单 Key',
    'documentation': '文档',
    'name': '名称',
    'id': '编号'
};

export default function customTranslate(template: string, replacements?: Record<string, any>) {
    replacements = replacements || {};

    // 翻译
    let result = translations[template] || template;

    // 替换参数
    return result.replace(/{([^}]+)}/g, function(_, key) {
        return replacements![key] !== undefined ? replacements![key] : '{' + key + '}';
    });
}
